name: darter
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Lenovo <Ztiany3@gmail.com>

environment:
  sdk: '>=2.19.6 <=3.9.3'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
dependencies:
  http: any
  dio: any
