name: Dart_Basic
description: A sample command-line application.

# version: 1.0.0
# homepage: https://www.example.com
# author: Lenovo <Ztiany3@gmail.com>
environment:
  sdk: '>=2.19.3 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.13.1
  http: ^0.13.5
  dio: ^5.0.1
